# Docker Compose: Simple HIL Testing Setup for CAN-enabled ECU

version: '3.8'

services:

  simulator:
    image: debian:bookworm-slim
    container_name: hil_simulator
    volumes:
      - ./simulation/Docker:/scripts
      - /lib/modules:/lib/modules:ro
    working_dir: /scripts
    command: ["bash", "/scripts/can_simulator.sh"]
    privileged: true
    network_mode: host

  can_logger:
    image: debian:bookworm-slim
    container_name: can_logger
    volumes:
      - ./logs:/logs
      - ./simulation/Docker:/scripts
      - /lib/modules:/lib/modules:ro
    working_dir: /scripts
    command: ["bash", "log_can.sh"]
    depends_on:
      - simulator
    privileged: true
    network_mode: host

  tester:
    image: python:3.11-slim
    container_name: hil_tester
    volumes:
      - ./tests:/tests
      - ./logs:/logs
    working_dir: /tests
    command: ["python", "run_tests.py"]
    depends_on:
      - simulator
      - can_logger
    privileged: true
    network_mode: host